// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

// Injectors from wire.go:

func InitMission(f FightParam, m MonsterParam) Mission {
	fighter := NewFighter(f)
	monster := NewMonster(m)
	mission := NewMission(fighter, monster)
	return mission
}
