// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/tag.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetTagListReq struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	State                uint32   `protobuf:"varint,2,opt,name=state,proto3" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTagListReq) Reset()         { *m = GetTagListReq{} }
func (m *GetTagListReq) String() string { return proto.CompactTextString(m) }
func (*GetTagListReq) ProtoMessage()    {}
func (*GetTagListReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_48dc6f15189f1be6, []int{0}
}

func (m *GetTagListReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTagListReq.Unmarshal(m, b)
}
func (m *GetTagListReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTagListReq.Marshal(b, m, deterministic)
}
func (m *GetTagListReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTagListReq.Merge(m, src)
}
func (m *GetTagListReq) XXX_Size() int {
	return xxx_messageInfo_GetTagListReq.Size(m)
}
func (m *GetTagListReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTagListReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetTagListReq proto.InternalMessageInfo

func (m *GetTagListReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GetTagListReq) GetState() uint32 {
	if m != nil {
		return m.State
	}
	return 0
}

type Tag struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	State                uint32   `protobuf:"varint,3,opt,name=state,proto3" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Tag) Reset()         { *m = Tag{} }
func (m *Tag) String() string { return proto.CompactTextString(m) }
func (*Tag) ProtoMessage()    {}
func (*Tag) Descriptor() ([]byte, []int) {
	return fileDescriptor_48dc6f15189f1be6, []int{1}
}

func (m *Tag) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Tag.Unmarshal(m, b)
}
func (m *Tag) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Tag.Marshal(b, m, deterministic)
}
func (m *Tag) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Tag.Merge(m, src)
}
func (m *Tag) XXX_Size() int {
	return xxx_messageInfo_Tag.Size(m)
}
func (m *Tag) XXX_DiscardUnknown() {
	xxx_messageInfo_Tag.DiscardUnknown(m)
}

var xxx_messageInfo_Tag proto.InternalMessageInfo

func (m *Tag) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Tag) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Tag) GetState() uint32 {
	if m != nil {
		return m.State
	}
	return 0
}

type GetTagListResp struct {
	Tags                 []*Tag   `protobuf:"bytes,1,rep,name=tags,proto3" json:"tags,omitempty"`
	Pager                *Pager   `protobuf:"bytes,2,opt,name=pager,proto3" json:"pager,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTagListResp) Reset()         { *m = GetTagListResp{} }
func (m *GetTagListResp) String() string { return proto.CompactTextString(m) }
func (*GetTagListResp) ProtoMessage()    {}
func (*GetTagListResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_48dc6f15189f1be6, []int{2}
}

func (m *GetTagListResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTagListResp.Unmarshal(m, b)
}
func (m *GetTagListResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTagListResp.Marshal(b, m, deterministic)
}
func (m *GetTagListResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTagListResp.Merge(m, src)
}
func (m *GetTagListResp) XXX_Size() int {
	return xxx_messageInfo_GetTagListResp.Size(m)
}
func (m *GetTagListResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTagListResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetTagListResp proto.InternalMessageInfo

func (m *GetTagListResp) GetTags() []*Tag {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *GetTagListResp) GetPager() *Pager {
	if m != nil {
		return m.Pager
	}
	return nil
}

func init() {
	proto.RegisterType((*GetTagListReq)(nil), "proto.GetTagListReq")
	proto.RegisterType((*Tag)(nil), "proto.Tag")
	proto.RegisterType((*GetTagListResp)(nil), "proto.GetTagListResp")
}

func init() {
	proto.RegisterFile("proto/tag.proto", fileDescriptor_48dc6f15189f1be6)
}

var fileDescriptor_48dc6f15189f1be6 = []byte{
	// 223 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x8f, 0xc1, 0x4a, 0xc4, 0x30,
	0x10, 0x86, 0x4d, 0xb2, 0x15, 0x9c, 0x75, 0x57, 0x18, 0x56, 0x28, 0x7b, 0x90, 0x92, 0x53, 0x4f,
	0x2b, 0xd4, 0x93, 0x78, 0xf0, 0x28, 0x82, 0x07, 0x89, 0x79, 0x81, 0x71, 0x37, 0x84, 0x1c, 0xda,
	0xc4, 0x26, 0xf8, 0xfc, 0x62, 0x52, 0xb4, 0x0b, 0x3d, 0x65, 0xf2, 0xcd, 0xe4, 0xfb, 0x33, 0x70,
	0x13, 0x46, 0x9f, 0xfc, 0x7d, 0x22, 0x7b, 0xc8, 0x15, 0x56, 0xf9, 0xd8, 0x63, 0xe1, 0x47, 0xdf,
	0xf7, 0x7e, 0x28, 0x2d, 0xf9, 0x08, 0x9b, 0x17, 0x93, 0x34, 0xd9, 0x37, 0x17, 0x93, 0x32, 0x5f,
	0x88, 0xb0, 0x1a, 0xa8, 0x37, 0x35, 0x6b, 0x58, 0x7b, 0xa5, 0x72, 0x8d, 0x3b, 0xa8, 0x62, 0xa2,
	0x64, 0x6a, 0xde, 0xb0, 0x76, 0xa3, 0xca, 0x45, 0x3e, 0x83, 0xd0, 0x64, 0x71, 0x0b, 0xdc, 0x9d,
	0xf2, 0xb8, 0x50, 0xdc, 0x9d, 0xfe, 0x04, 0x7c, 0x49, 0x20, 0xe6, 0x02, 0x0d, 0xdb, 0x79, 0x76,
	0x0c, 0x78, 0x07, 0xab, 0x44, 0x36, 0xd6, 0xac, 0x11, 0xed, 0xba, 0x83, 0xf2, 0xc7, 0x83, 0x26,
	0xab, 0x32, 0x47, 0x09, 0x55, 0x20, 0x6b, 0xc6, 0x2c, 0x5f, 0x77, 0xd7, 0xd3, 0xc0, 0xfb, 0x2f,
	0x53, 0xa5, 0xd5, 0xbd, 0x02, 0x68, 0xb2, 0x1f, 0x66, 0xfc, 0x76, 0x47, 0x83, 0x4f, 0x00, 0xff,
	0x19, 0xb8, 0x9b, 0x1e, 0x9c, 0xad, 0xbc, 0xbf, 0x5d, 0xa0, 0x31, 0xc8, 0x8b, 0xcf, 0xcb, 0xcc,
	0x1f, 0x7e, 0x02, 0x00, 0x00, 0xff, 0xff, 0xbd, 0xdd, 0xbd, 0x65, 0x51, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// TagServiceClient is the client API for TagService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TagServiceClient interface {
	GetTagList(ctx context.Context, in *GetTagListReq, opts ...grpc.CallOption) (*GetTagListResp, error)
}

type tagServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTagServiceClient(cc grpc.ClientConnInterface) TagServiceClient {
	return &tagServiceClient{cc}
}

func (c *tagServiceClient) GetTagList(ctx context.Context, in *GetTagListReq, opts ...grpc.CallOption) (*GetTagListResp, error) {
	out := new(GetTagListResp)
	err := c.cc.Invoke(ctx, "/proto.TagService/GetTagList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TagServiceServer is the server API for TagService service.
type TagServiceServer interface {
	GetTagList(context.Context, *GetTagListReq) (*GetTagListResp, error)
}

// UnimplementedTagServiceServer can be embedded to have forward compatible implementations.
type UnimplementedTagServiceServer struct {
}

func (*UnimplementedTagServiceServer) GetTagList(ctx context.Context, req *GetTagListReq) (*GetTagListResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTagList not implemented")
}

func RegisterTagServiceServer(s *grpc.Server, srv TagServiceServer) {
	s.RegisterService(&_TagService_serviceDesc, srv)
}

func _TagService_GetTagList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTagListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TagServiceServer).GetTagList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.TagService/GetTagList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TagServiceServer).GetTagList(ctx, req.(*GetTagListReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _TagService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.TagService",
	HandlerType: (*TagServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetTagList",
			Handler:    _TagService_GetTagList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/tag.proto",
}
