global:
  scrape_interval: 15s
  external_labels:
    monitor: 'calculate-monitor'

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']
        labels:
          group: 'local'

  - job_name: 'calculate'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9000']
        labels:
          group: 'calculate'